[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "PySelenScrapr"
authors = [{name = "donnercody", email = "donnercody86@gmail.com"}]
dynamic = ["version", "description"]